services:
  app:
    build: .
    container_name: bidding_document_generator-app
    environment:
      # 如有需要自行添加代理或其他环境变量
      - PYTHONPATH=/app
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - ALIYUN_API_KEY=your_api_key
    ports:
      - "8000:8000"  # 如果你的 Flask/FastAPI 等服务监听8000端口，可调整
    depends_on:
      - neo4j
    volumes:
      - .:/app  # 如不希望本地代码覆盖容器代码可去掉
  neo4j:
    image: neo4j:5.19.0-community
    container_name: bidding_document_generator-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"   # Neo4j 浏览器 Web
      - "7687:7687"   # Neo4j Bolt 协议
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: